---
name: Production Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    if: github.actor != 'adp-devsite-app[bot]' && github.repository != 'AdobeDocs/dev-docs-template'
    uses: AdobeDocsPrivate/adp-devsite-workflow-private/.github/workflows/deploy-v2.yml@main
    secrets: inherit
    with:
      env: prod